# Header
menu:
  主页: //www.hufeifei.cn
  博客: /
  归档: /archives
  算法: //algo.hufeifei.cn
  书籍: /book
rss: /atom.xml
github: /github

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: right
widgets:
- wechat
- tencent_ads
- category
#- tag
- tagcloud
# - archive
- recent_posts
- ads_unit

wechat: //www.hufeifei.cn/wechat-public-account.jpg

footer:
  since: 2016
  power_by: true
  beian: 
    enable: true
    icp: 赣ICP备17009276号


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics: true
gauges_analytics:
favicon: //www.hufeifei.cn/favicon.jpg
twitter:
fb_admins:
fb_app_id:

# waline comment system. https://waline.js.org
waline:
  enable: true
  serverURL: 'https://api.waline.blog.hufeifei.cn'
  avatar: 'mp'
  pageSize: 10 # comment list page size
  lang: zh-cn # i18n: zh-cn/en
  placeholder: Just go go
  visitor: true
  recordIP: true
  requiredFields: ['nick']

google_ads:
  enable: true
  ad_client: ca-pub-7111912103882824
  js: https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-7111912103882824

reward: 
  enable: true
  alipay: https://www.hufeifei.cn/reward-img/alipay.jpg
  wechat: https://www.hufeifei.cn/reward-img/wechat.jpg

vendors: 
  # FancyBox
  # jquery: //cdn.jsdelivr.net/npm/jquery@3/dist/jquery.min.js
  jquery: //cdnjs.loli.net/ajax/libs/jquery/3.0.0/jquery.min.js
  # fancybox: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.js
  fancybox: //cdnjs.loli.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.js
  # fancybox_css: //cdn.jsdelivr.net/gh/fancyapps/fancybox@3/dist/jquery.fancybox.min.css
  fancybox_css: //cdnjs.loli.net/ajax/libs/fancybox/3.5.7/jquery.fancybox.min.css

  swiper: //cdn.bootcdn.net/ajax/libs/Swiper/11.0.5/swiper-bundle.min.js
  swiper_css: //cdn.bootcdn.net/ajax/libs/Swiper/11.0.5/swiper-bundle.min.css

  # FontAwesome
  #fontawesome: //cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/all.min.css
  fontawesome: //cdnjs.loli.net/ajax/libs/font-awesome/5.15.3/css/all.min.css

  # waline
  waline: //unpkg.com/@waline/client@v3/dist/waline.css

  other_css:
    - //at.alicdn.com/t/font_841402_efkj8jo1xld.css

ads:
  enabled: true
  # https://swiperjs.com/swiper-api
  swiper_options:
    slidesPerView: 1
    spaceBetween: 10
    loop: true
    autoplay:
      delay: 2500
      disableOnInteraction: false
  assets:
    - title: 【腾讯云】云服务器、云数据库、COS、CDN、短信等云产品特惠热卖中
      url: https://curl.qcloud.com/8E3CrC3m
      img: https://dscache.tencent-cloud.cn/upload//345_200-013e419e2b86ff48a531fabce2694bd3bb27f844.png
    - title: 【腾讯云】Lighthouse助力跨境电商业务扬帆出海
      url: https://curl.qcloud.com/wVGSgyE8
      img: https://dscache.tencent-cloud.cn/upload//rhino-design-345x200-4c873fb0a9753759ae4932e2e1e212715fa7f06b.png
    - title: 买云服务器，参与礼品兑换、抽奖，最高送价值8000元IPad，还有Bose耳机、千元京东卡等您来！
      url: https://curl.qcloud.com/gze2lfYy
      img: https://upload-dianshi-1255598498.file.myqcloud.com/%E4%BC%81%E4%B8%9A%E7%9B%9B%E5%A4%8F%E6%9C%89%E7%A4%BC-345x200-d2146292109c1c9e1ae000a6c3ecde162d89e493.jpg
    - title: DNSPod解析套餐全面升配降价，更高的套餐配置规格，更优的价格方案，全面提升可用性及响应率，专业版限时99元/年！
      url: https://curl.qcloud.com/LonPwhxX
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345x200%E9%8D%93%EE%88%9B%E6%B9%B0-82de69db27c1e7984b871bdba4ea3dd5d5acda1f.jpg
    - title: 云产品限时秒杀，爆款1核2G云服务器，首年74元
      url: https://curl.qcloud.com/7ec01pIF
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345-200-788d0ee3eed06e913b85ddb6b178f8b9960c4684.jpg
    - title: 中小企业福利专场，多款刚需产品，满足企业通用场景需求，云服务器2.5折起
      url: https://curl.qcloud.com/qbSzF0sM
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345-200-b28f7dee9552f4241ea6a543f15a9798049701d4.jpg
    - title: ElasticSearch新用户特惠，快速实现日志分析、应用搜索，首购低至4折
      url: https://curl.qcloud.com/hDCEkRsS
      img: https://upload-dianshi-1255598498.file.myqcloud.com/%E8%85%BE%E8%AE%AF%E4%BA%913_345%20200_1-7aeb8eb451fd6de33676444898914b1ff3298996.jpg
    - title: 腾讯云数据库性能卓越稳定可靠，为您解决数据库运维难题
      url: https://curl.qcloud.com/YjfBwRLm
      img: https://upload-dianshi-1255598498.file.myqcloud.com/%E5%85%A5%E9%97%A8%E4%BA%91%E6%95%B0%E6%8D%AE%E5%BA%93MYSQL-345x200-a68c566987f9bf687433e2cf4fbdc85ece6e2d93.jpg
    - title: 腾讯云图，像PPT一样简单的数据可视化工具。5元搞定数据可视化，模板丰富，拖拖拽拽就能做出好看的可视化大屏。
      url: https://curl.qcloud.com/SDMIWAoV
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345x200-89eeba55a2f49008e686e1a51e14bfe79f63af13.png
    - title: 视频通信爆款 9.9 元起， 提供电商、教育、社交娱乐等多行业多场景的一站式解决方案，最快 1 天布局火爆赛道
      url: https://curl.qcloud.com/8DvMAlwF
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345_200-51cc0ac5a1b375c4269c679987e3bc7c62a2c592.png
    - title: 即时通信 IM 首购 1 折特惠，仅需99.9元/月，支持直播电商、在线教育等多种热门应用场景
      url: https://curl.qcloud.com/VbUAuJ2j
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345_200%E5%A4%87%E4%BB%BD-15e14b2502f1e6df9e647ba452416d4a4f3dda04.png
    - title: 9.9元体验2万分钟实时音视频通话,支持1对1或多人音视频通话,单房可支持300人同时在线，10万人同时观看；全平台互通高品质通话
      url: https://curl.qcloud.com/6HS1Q41a
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345_200%E5%A4%87%E4%BB%BD%202-15a05a841743ffd2dc01731972dd7b3c2b46e357.png
    - title: 专业版APP加固特惠5折起，可享免费兼容性测试
      url: https://curl.qcloud.com/pcReLJBk
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345x200-5d6e2cf6805432934eeb9f7800bd1a5d282906ae.jpg
    - title: 新客户首购 TPNS 特惠9.8元/万 DAU，新老客户低至6.5折，给您提供快速、稳定、安全、高效的用户促活利器
      url: https://curl.qcloud.com/xwWYC6oW
      img: https://upload-dianshi-1255598498.file.myqcloud.com/345_200%E5%A4%87%E4%BB%BD%203-9f78293b201220263799ac53f85ae6cd13e0e8a7.png
